### ISSUE TITLE
Output whats happening on the server to a console

### ISSUE THREAD

**Issue by Reviville** [itzg/dockerfiles#157] opened 2017-06-07 17:35 UTC
Hey ho it's me again,

let me explain what i thought about this time.

Theres 3 ways to look onto the server and see whats going on:
1. way is to attach to it
2. way is to execute docker logs...
3. way is to "less logs/latest.log"

now i want to display whats happening on the server directly to a webinterface console... but i cant use the docker attach function, as i put in the option "--noconsole"
i cant use docker logs, because there is stuff the console should not output (like the echos in the beginning)
the 3rd way would be possible, but first of all takes too much time, consumpts a lot of network if its big and last but not least is just a crappy solution... :D

Any ideas?

**Comment by itzg** [comment] 2017-06-08 01:26
I could create and include a helper tool that interprets the log and emits a summary of it. That would get the best of approach three but minimize the volume of network output. 

Otherwise the rcon-cli might be helpful. 

What kinds of info do you want to extract from the logs/system?

**Comment by Reviville** [comment] 2017-06-08 12:49
i would like to have everything that is displayed in the minecraft logs under logs/latest.log basically

so everything the minecraft server echoes when running in a screen for example.
i dont want to see the echoes from the docker (switching to user minecraft, downloading.. etc.)

for example:
![image](https://user-images.githubusercontent.com/26972387/26929351-988f720e-4c59-11e7-8ddd-43be2a597b42.png)

**Comment by dschaper** [comment] 2017-06-08 19:31
This might be worth a look at tmux or screen inside the container. Having that would allow you to attach the container and see the terminal scroll. (Not sure if that would also help with the situations where CPU pegs?) Or is this more about an aggregate copy of the logs for other processing offline?

**Comment by Reviville** [comment] 2017-06-09 14:18
its more like displaying live ( in real time) what is happening on the server on a webserver.
basically i want a console on the web and then send commands to the server and directly get the result back - same as sitting there and watching the console without docker.

**Comment by itzg** [comment] 2017-06-09 17:04
Thinking outside the box (or container :) ), perhaps a more direct/efficient solution is to leave the minecraft server logging to console **but** start your container with the gelf-log-driver to send the minecraft server output to a central location of your choosing:

https://docs.docker.com/engine/admin/logging/gelf/

Otherwise, docker exec'ing into the container and using rcon-cli might address some other data points. And then finally, there are implementations (in Java for sure) of the Minecraft server protocol where you can do some basic interrogation of the server state. Here's an example of where I do that:

https://sourcegraph.com/github.com/moorkop/mccy-engine@master/-/blob/src/main/java/me/itzg/mccy/services/impl/ServerStatusServiceImpl.java#L51-82

**Comment by dschaper** [comment] 2017-06-09 19:30
https://hub.docker.com/r/gliderlabs/logspout/ May be an easier to implement solution. I use it quite extensively to route logs to ELK stacks and it's really solid. I do have a couple of other points, but I'll raise those as other Feature Request issues as to not clutter here.

**Comment by itzg** [comment] 2017-06-09 22:51
Yes, I forgot about logspout. That one is interesting since I believe you can still `docker log` concurrently into each container.

**Comment by dschaper** [comment] 2017-06-10 00:19
Yeah, it basically takes whatever is on stdour/stderr and outputs that to your end target. The `docker log` `docker-compose logs` still show as does anything that you would see on an attach to the container.

**Comment by itzg** [comment] 2017-06-10 20:00
The logspout approach got me curious about something and by running 

    ls -l /var/lib/docker/containers/*/*-json.log

I confirmed that the [default json file logger](https://docs.docker.com/engine/admin/logging/json-file/#options) does not use a `max-size` by default and I have some logs that are several hundred MB now.

So I advise anyone that uses logspout to also tune their `log-opt`s

**Comment by itzg** [comment] 2017-06-10 20:50
I finally got around to using the gelf driver on my home system and I am quite impressed with the details that come along with each log document:

```
{
        "_index": "logstash-2017.06.10",
        "_type": "logs",
        "_id": "AVyTu4Gn1ahRCX9Qrxm-",
        "_score": 1,
        "_source": {
          "source_host": "172.22.0.1",
          "level": 6,
          "created": "2017-06-10T20:39:13.33070792Z",
          "message": """{"type":"log","@timestamp":"2017-06-10T20:39:17Z","tags":["status","plugin:elasticsearch@5.4.0","info"],"pid":12,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}""",
          "version": "1.1",
          "command": "/docker-entrypoint.sh kibana",
          "image_name": "kibana",
          "@timestamp": "2017-06-10T20:39:17.446Z",
          "container_name": "nuces_kibana_1",
          "host": "nuc",
          "@version": "1",
          "tag": "cc9be6fce6d3",
          "image_id": "sha256:1dfc1de100f14c4698772801247f940a752cc41160dd2657a38d472a76d7ea50",
          "container_id": "cc9be6fce6d3ed4b2ca32d86acaf50148164eb75ad05680730fd652789c1a53e"
        }
      }
```

I thought I'd try the new official logstash image from Elastic, so a heads up that not disabling `XPACK_MONITORING_ENABLED` bit me at first. Here's my compose snippet:

```yaml
  logstash:
    image: docker.elastic.co/logstash/logstash:5.4.1
    environment:
      XPACK_MONITORING_ENABLED: "false"
    ports:
     - "12201:12201/udp"
    volumes:
      - "${PWD}/logstash-pipeline:/usr/share/logstash/pipeline/:ro"
    restart: always
```

**Comment by itzg** [comment] 2017-06-10 20:51
...looks like I should play with logstash further decoding the "message" as the JSON payload it seems to be (in the case of kibana's output).

**Comment by itzg** [comment] 2017-06-10 21:04
FYI here's what I have deployed at home for my "ELK" composition:

https://github.com/itzg/nuc-es/blob/master/docker-compose.yml

**Comment by dschaper** [comment] 2017-06-10 21:37
5.4.0 comes with X-pack now doesn't it?

**Comment by itzg** [comment] 2017-06-10 22:57
Ah, they pre-bundle x-pack in their images, but with a 30 day trial.

**Comment by dschaper** [comment] 2017-06-11 00:27
Good, we've licensed, but thanks for the confirmation...

**Comment by itzg** [comment] 2017-06-19 18:27
@Reviville are you good with me closing this issue? Sounds like streaming the logging via logstash worked for you, right?

**Comment by Reviville** [comment] 2017-06-20 07:34
@itzg sure go ahead, i ended up with using gelf and logstash but im still trying to remove the unwanted echoes. But again, thank you very much :)

**Closed** 2017-06-22 00:21 UTC
Labels: waiting on feedback, what/minecraft-server
