### ISSUE TITLE
How can we go inside individual container?

### ISSUE THREAD

**Issue by masifpak** [itzg/dockerfiles#56] opened 2016-01-27 14:16 UTC
How can we go inside the individual container.

$ sudo docker attach es0    (But no to avail.)

**Comment by itzg** [comment] 2016-01-27 14:39
@masifpak , if you're wanting to go into a container to inspect and edit the file system, such as configuration files, then use [docker exec](https://docs.docker.com/engine/reference/commandline/exec/).

**Comment by masifpak** [comment] 2016-01-28 06:01
Actually i installed ssh and supervisor. In supervisor.conf I added the following lines.

[supervisord]
nodaemon=true
[program:sshd]
command=/usr/sbin/sshd -D
[program:elasticsearch]
command=/bin/bash -c "/start"

In docker file I just replaced start script with    CMD ["/usr/bin/supervisord"]
But when I run this container, it just exited. How can I troubleshoot the reason of exit.

**Comment by itzg** [comment] 2016-01-28 14:06
Even though using supervisord to add ssh into the container is technically valid, it is actually one of the [Docker anti-patterns](http://techblog.constantcontact.com/devops/a-tale-of-three-docker-anti-patterns/). Did `docker exec` not achieve what you needed?

As far as troubleshooting, see if `docker logs` reveals anything about the failure.

**Comment by masifpak** [comment] 2016-01-29 07:24
Good. I read Docker anti-patterns. I should not use ssh. Please help me understanding some part of Dockerfile and start script.

**# ## Dockerfile**
1- touch /data/.CREATED /conf/.CREATED        # Why to create ".CREATED" files.
2- VOLUME ["/data","/conf"]                                # /data and /conf is being mount on host machine so that elastic data store on host to avoid container getting large.

3- USER elasticsearch                                   # Does it mean every thing run in container with this user

4- ENV OPTS=-Dnetwork.host=_non_loopback_   # I could not understand purpose of this command.and why assignment sign "="

## # start script****

Please give some explanation of the following script part.

5-  if [ -f /conf/env ]; then
        . /conf/env                                                       # what is doing this " . /conf/env"  
     fi

6-  OPTS="$OPTS   -Des.path.conf=/conf \
                                -Des.path.data=/data \
                                -Des.path.logs=/data \
                                -Des.transport.tcp.port=9300 \
                                -Des.http.port=9200"

I know what is happening here but how we are assigning multiple parameters in one variable.

7-  if [ -n "$CLUSTER" ]; then
  OPTS="$OPTS -Des.cluster.name=$CLUSTER"
  if [ -n "$CLUSTER_FROM" ]; then
    if [ -d /data/$CLUSTER_FROM -a  !  -d /data/$CLUSTER ]; then
      echo "Performing cluster data migration from $CLUSTER_FROM to $CLUSTER"
      mv /data/$CLUSTER_FROM /data/$CLUSTER
    fi
  fi
fi

In this part where it is taking cluster name from and why migration in just creating ES cluster.

8- if [ -n "$PUBLISH_AS" ]; then
  OPTS="$OPTS -Des.transport.publish_host=$(echo $PUBLISH_AS | awk -F: '{print $1}')"
  OPTS="$OPTS -Des.transport.publish_port=$(echo $PUBLISH_AS | awk -F: '{if ($2) print $2; else print 9300}')"
fi

#What is being done in second OPTS.

9- if [ -n "$PLUGINS" ]; then
  for p in $(echo $PLUGINS | awk -v RS=, '{print}')
  do
    echo "Installing the plugin $p"
    $ES_HOME/bin/plugin install $p
  done
fi

# Which plugins are in PLUGIN directory.

**Comment by masifpak** [comment] 2016-01-29 10:19
One more thing.

when i run container without volumes mapping it run fine.
sudo docker run -h es0 --name es0 -d -p 9200:9200 -p 9300:9300 es:latest

but when i run using volumes as below it sends permission error. Any clue please?

sudo docker run  -it -h es0 --name es0  -v /opt/oescluster/es0/data:/data:rw -v /opt/oescluster/es0/conf:/conf:rw   -p 9200:9200 -p 9300:9300 es:latest

cp: cannot create regular file '/conf/elasticsearch.yml': Permission denied
cp: cannot create regular file '/conf/logging.yml': Permission denied
Starting Elasticsearch with the options -Dnetwork.host=_non_loopback_ -Des.path.conf=/conf   -Des.path.data=/data   -Des.path.logs=/data   -Des.transport.tcp.port=9300   -Des.http.port=9200

**Comment by itzg** [comment] 2016-01-29 14:56
Deep questions :) Let me see if I can remember what all I was doing there:

First some background about container UIDs. Related to this issue https://github.com/docker/docker/issues/7198, coordinating the file ownership of attached volumes gets a little strange when the container UID (elasticsearch=999 in this case) does not match an existing host UID. FYI, here's how I confirmed the container UID of elasticsearch:

```bash
> docker run --rm itzg/elasticsearch id elasticsearch
uid=999(elasticsearch) gid=999(elasticsearch) groups=999(elasticsearch)
```

Your follow-on observation about "Permission denied" is related to this. If you run just 

    id

on your host system, I'm guessing the uid does not match the container's 999.  I haven't tried this lately, but overriding `USER` with `-u`, [as described here](https://docs.docker.com/engine/reference/run/#user), to match what your `id` reports will probably resolve this.

1. Since I wanted the container process to run as non-ROOT, later in the Dockerfile with a `USER elasticsearch`, I found I had to pre-create the volume attach point and fix the directory ownership. This might have since been fixed in Docker, but creating empty directories wasn't enough. I needed to put a placeholder file in there, hence the `touch`

2. Partially correct. A container getting large is actually not a problem as long as you have a sufficiently large `/var/lib/docker` filesystem. On some of my systems I dedicate a separate LVM space for that mount point specifically. With 1.9+, `docker volume` has become an elegant way to further tune the backing store of volumes rather than attaching host directories to achieve the same. In fact, you can use alternate technologies like [GlusterFS](https://github.com/calavera/docker-volume-glusterfs) to back the volumes.

3. Yes. By default, container processes run as root. I'm personally not convinced that's all that bad, but there's plenty of discussion out there that claims to be very nervous about running application processes as root...even within a container (kernel control group and namespace).

4. That gets passed as-is to the Java invocation of the Elasticsearch service itself, hence the `=` within the assignment. As for `non_loopback`, please refer to [here for background](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html#modules-network). Keep in mind that the IP address selected would still be "container local", so only containers on the same Docker network can resolve to it.

5. That was a little trick I introduced when I needed to override the `-e` settings of the original container creation, such as changing cluster membership. What I do is `docker exec` into the container, add the overrides to `/conf/env` and restart the container to pick up the environment change.

6. Later `$OPTS` gets passed as a bare string to the Java invocation. At that point, Java will interpret each `-Dvar=value` part as an argument each.

7.  This is the second half of the trick I introduced at 5. In order to migrate an existing ES node from one cluster to another with all possible data retention, the cluster-named data directory (an ES convention) needs to be renamed or else the existing node joining the new cluster starts with an empty data directory. This technique might warrant a wiki page, if you're interested in me going deeper into this.

8. That's to be flexible and allow `PUBLISH_AS` to be given as just "es-host" or "es-host:9304" where the later declares a specific port. In the first, case a default transport port of 9300 is used.

9. `PLUGIN` doesn't refer to a directory, but rather a comma separate list of community ES plugins, as [described here](https://www.elastic.co/guide/en/elasticsearch/plugins/2.1/installation.html#installation)

**Comment by itzg** [comment] 2016-02-02 17:54
I'm closing to close out the issue, but @masifpak , feel free to ask more questions as they come up.

**Closed by itzg** 2016-02-02 17:54 UTC
